Main

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -28,10 +28,8 @@ jobs:
         script: |
           echo "Current directory:"
           pwd
-          echo "Listing /public_html contents:"
-          ls -la /public_html/
-          echo "Changing to /public_html/transit:"
-          cd /public_html/transit || { echo "Failed to change directory"; exit 1; }
+          echo "Changing to /home/u992053974/public_html/transit:"
+          cd /home/u992053974/public_html/transit || { echo "Failed to change directory"; exit 1; }
           echo "Current directory after cd:"
           pwd
           echo "Listing current directory contents:"
